---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wpextdb
spec:
  selector:
    matchLabels:
      app: wpextdb
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wpextdb
        tier: frontend
    spec:
      containers:
      - image: wordpress:cli-2-php7.3
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wpextdb-svc
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wpdb-secret
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wpdb-secret
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wpdb-pvc
